{% set name = "SoapySDR" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pothosware/{{ name }}/archive/soapy-sdr-{{ version }}.tar.gz
  sha256: a508083875ed75d1090c24f88abef9895ad65f0f1b54e96d74094478f0c400e6
  patches:
    - 0001-Get-Python-extension-suffix-from-sysconfig-and-set-i.patch

build:
  number: 3
  run_exports:
    - {{ pin_subpackage('soapysdr', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - swig
    # cross-compilation dependencies
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
  run:
    - python

test:
  commands:
    # verify that executables can be run
    - SoapySDRUtil --info

    # verify that (some) headers get installed
    - test -f $PREFIX/include/{{ name }}/Version.h  # [not win]
    - test -f $PREFIX/include/{{ name }}/Version.hpp  # [not win]
    - if not exist %PREFIX%\\Library\\include\\{{ name }}\\Version.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\include\\{{ name }}\\Version.hpp exit 1  # [win]

    # verify that libraries get installed
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\{{ name }}.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\{{ name }}.lib exit 1  # [win]
  imports:
    - SoapySDR

about:
  home: https://github.com/pothosware/SoapySDR/wiki
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: Vendor and platform neutral SDR support library
  description: |
    SoapySDR is an open-source generalized API and runtime library for interfacing with
    SDR devices. With SoapySDR, you can instantiate, configure, and stream with an SDR
    device in a variety of environments. Most off the shelf SDR hardware platforms are
    supported by SoapySDR, and many open source applications rely on SoapySDR for
    hardware integration support. In additon, SoapySDR has bindings for development
    frameworks like GNU Radio and Pothos.
  doc_url: https://github.com/pothosware/SoapySDR/wiki
  dev_url: https://github.com/pothosware/SoapySDR

extra:
  recipe-maintainers:
    - ryanvolz
